name: Validate JSON and YAML

on:
  push:
    paths:
      - "**.json"
      - "**.yaml"
      - "**.yml"
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate JSON files
        run: |
          find . -name "*.json" -print0 | xargs -0 -n1 jq .

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: Validate YAML files
        run: |
          yamllint .
